name: face_mood_light_detector
description: "Real-time face condition detection with emotion analysis and lighting adaptation."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  camera: ^0.11.0+2
  permission_handler: ^11.3.1
  wakelock_plus: ^1.2.8
  google_mlkit_face_detection: ^0.12.0
  image: ^4.3.0
  tflite_flutter: ^0.11.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
